version: '3.4'

services:
  server:
    build: .
    image: regexit/valheim-server:latest
    environment:
      - SERVER_PASSWORD=${SERVER_PASSWORD:-change-me}
      - SERVER_WORLD=${SERVER_WORLD:-Dedicated}
      - SERVER_NAME=${SERVER_NAME}
    volumes:
      - worlds:/home/steam/.config/unity3d/IronGate/Valheim/worlds:rw
    ports:
      - 2456:2456
      - 2457:2457
      - 2458:2458

volumes:
  worlds:
