version: '3.4'

services:
  server:
    build: .
    image: regexit/valheim-server:latest
    environment:
      - SERVER_PASSWORD=${SERVER_PASSWORD:-change-me}
      - SERVER_WORLD=${SERVER_WORLD:-Dedicated}
      - SERVER_NAME=${SERVER_NAME}
    volumes:
      - valheim:/home/steam/.config/unity3d/IronGate/Valheim:rw
    ports:
      - 0.0.0.0:2456:2456/udp
      - 0.0.0.0:2456:2456/tcp
      - 0.0.0.0:2457:2457/udp
      - 0.0.0.0:2457:2457/tcp
      - 0.0.0.0:2458:2458/udp
      - 0.0.0.0:2458:2458/tcp

volumes:
  valheim:
